---
- name: Copy repo file into place
  template:
    src: datadog-repo.j2
    dest: /etc/yum.repos.d/datadog.repo
    owner: root
    group: root
    mode: 0644
  tags:
    - datadog
    - yum

- name: Install datadog-agent package
  yum:
    name: datadog-agent
    state: latest
  tags:
    - datadog
    - yum

- name: Install datadog dependencies
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - ntplib
    - simplejson
  tags:
    - datadog
    - pip

- name: Create Datadog Config File
  copy:
    src: /etc/dd-agent/datadog.conf.example
    dest: /etc/dd-agent/datadog.conf
    remote_src: yes

- name: Set API Key in config
  replace:
    dest: /etc/dd-agent/datadog.conf
    regexp: 'api_key:\.*'
    replace: 'api_key: {{ datadog_api_key }}'
